C110 added a new end point to filter and fetch the tweets
SupriyaPamulapati/TweetMavin pull request #12
Opened 2021-11-21 11:57 UTC by SupriyaPamulapati

2021-11-22 11:52 UTC, anasuya1117 reviewed
Update the test cases and address the comments

2021-11-22 11:52 UTC, anasuya1117 commented on src/main/java/UTwitter/service/TwitterImplement.java
>          return arrayList;
arrayList is a data type in java, it's not a good variable name.

2021-11-22 11:52 UTC, anasuya1117 commented on src/main/java/UTwitter/service/TwitterImplement.java
> +        }
Apply DRY principle

2021-11-22 11:52 UTC, anasuya1117 commented on src/test/com/test/GetFilteredTweets_Test.java
> +        Assert.assertEquals(expectedTweet.getStatus(), actualTweet.getStatus());
match the data, status will be 200 ok for all cases.

2021-11-22 11:52 UTC, anasuya1117 commented on src/test/com/test/GetFilteredTweets_Test.java
> +        Assert.assertEquals(Arrays.asList(), actual);
Test is not clear. please update

2021-11-23 06:44 UTC, PoojaMohite-Khoros requested changes

2021-11-23 06:44 UTC, PoojaMohite-Khoros commented on src/main/java/UTwitter/resources/Controller.java
>  import UTwitter.service.TwitterImplement;
UTwitter , if this is package name , its not according to naming convention, please correct

2021-11-23 06:44 UTC, PoojaMohite-Khoros commented on src/test/com/test/GetFilteredTweets_Test.java
> +public class GetFilteredTweets_Test {
File names usually doesn't have underscores so please check with 
Naming conversion link that I had sent in channel

2021-11-23 10:51 UTC, PoojaMohite-Khoros approved these changes
We can always improve the filter.
Please merge and create PR for next lab

2021-11-23 10:54 UTC, merged